### ISSUE TITLE
加载速度

### ISSUE THREAD

**Issue by Narutojoy** [monlor/docker-xiaoya#102]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
每次第一次打开app进入首页，需等待12秒左右才能完全加载（即图片全部显示）。完全加载后再点选或者滑动海报墙速度就很快了。
另外每次搜索一个片子，也需要等待12秒左右。
不知道是我设置不对还是片量过大所致。

**重现步骤**
复现问题的步骤:
1. 如上所述

**预期行为**
第一次进入app更快的加载首页。
搜索影片速度更快。

**截图**
无。

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
无。

---

**Comment by monlor** [comment]
元数据+媒体数据都有60G，加载时间长很正常
