### ISSUE TITLE
剧集貌似不能同步更新

### ISSUE THREAD

**Issue by Narutojoy** [monlor/docker-xiaoya#103]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
部分剧集貌似不能同步更新（我己经将emby的api手动添加到docker-compose最下方处）
比如时光正好这部，我在alist中看到已经到17集了，但是在emby中还是第8集，已经等了2晚上。
看日志确实晚上3点有关闭和重启的动作，且重启成功。
想确认下，自动重启容器的动作是在更新嘛。

**重现步骤**
复现问题的步骤:
如上所属

**预期行为**
emby能正常更新alist，alist里有哪些，emby就有哪些

**截图**
![image](https://github.com/monlor/docker-xiaoya/assets/25220944/37682549-a361-4da3-965d-b32b06a7da49)
![image](https://github.com/monlor/docker-xiaoya/assets/25220944/15e8a228-44a2-4338-a750-20ff32b4ff13)

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
无。

---

**Comment by monlor** [comment]
自己刷，这个看小雅更不更新

**Comment by Narutojoy** [comment]
> 自己刷，这个看小雅更不更新

想问下大佬，自己刷是去时光正好里面手动刷新元数据？还是说要等alist里的元数据文件夹里的几个东西更新才行呀

**Comment by monlor** [comment]
emby刷新，刷新没用就是emby里的数据还没更新

**Comment by Narutojoy** [comment]
> emby刷新，刷新没用就是emby里的数据还没更新

了解
想确认下小雅如果不更新这三个文件，那emby里永远不会改变是吗😂
![image](https://github.com/monlor/docker-xiaoya/assets/25220944/0c72aff9-5e6d-416a-955f-f8d118283b33)

**Comment by monlor** [comment]
每日更新里的数据是每天更新

**Comment by Narutojoy** [comment]
> 每日更新里的数据是每天更新

了解了。
几个“每天更新”系列如果没有，就只能等小雅更新元数据了吧
或者等不及的直接去alist里看嘛哈哈哈哈
