### ISSUE TITLE
Jellyfin元数据下载报错

### ISSUE THREAD

**Issue by inadavid** [monlor/docker-xiaoya#106]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
安装alist+Jellyfin选项时，metadata 容器log反复出现以下内容：
alist浏览及在线观看功能没有问题。 tvbox也可以正常的调取alist进行播放。
```log
开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
Downloading Jellyfin config...
Downloading config_jf.mp4...
Downloading config_jf.mp4, try 1...

06/13 10:05:14 [NOTICE] Downloading 1 item(s)

06/13 10:05:14 [NOTICE] Download complete: /media/temp/config_jf.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8003ee|OK  |    48KiB/s|/media/temp/config_jf.mp4

Status Legend:
(OK):download completed.
Download config_jf.mp4 failed.
等待alist启动完成...
alist启动完成，可能需要一段时间加载数据，等待5分钟后开始下载元数据...
``` 

**重现步骤**
复现问题的步骤:
正常安装alist+Jellyfin即可复现

**预期行为**
消除问题

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

---

**常见问题**

如果你的问题不在此列表中，仍然需要提问，请删除**常见问题**这块内容再提交问题

* 获取file id失败：1. 请检查你的阿里云盘token，opentoken和folderid配置是否正确，2. 阿里云盘空间是否饱和，3. 多次尝试更换token和opentoken。

**Comment by ff522** [comment]
这是什么服务出错了吗,这个issue下面那个也是同样问题

**Comment by xiaoweihong** [comment]
也一样，同样的报错

**Comment by Techeek** [comment]
同样问题，辛苦开发者看看，谢谢

**Comment by langzizhui** [comment]
同样的问题

**Comment by monlor** [comment]
优化了一下元数据状态检查和下载流程

**Comment by hot323** [comment]
同样的问题，看过去应该是alist元数据目录下没有 config_jl.mp4这个文件。

**Comment by monlor** [comment]
#105

**Comment by wt7060** [comment]
同样问题，我也是以上错误，请修复，目前只能用emby，jellyfin的元数据解压一直报错：
======+====+===========+=======================================================
626450|OK  |    32KiB/s|/media/temp/config_jf.mp4
Status Legend:
(OK):download completed.
Download config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
Downloading config_jf.mp4, try 5...
Link is http://alist:5678/d/元数据/config_jf.mp4
02/05 17:05:55 [NOTICE] Downloading 1 item(s)
02/05 17:05:55 [NOTICE] Download complete: /media/temp/config_jf.mp4
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
NAS品牌：UGREEN
