### ISSUE TITLE
扫库时间巨长

### ISSUE THREAD

**Issue by Narutojoy** [monlor/docker-xiaoya#111]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
每次手动扫描库的时间巨长，一个电视剧可能需要好几个小时，一直卡在98%，但我看占用也不高，也没有一直下载什么东西，不知道什么原因

**重现步骤**
复现问题的步骤:
1. 手动扫描媒体库

**预期行为**
更快速的完成扫描。

**截图**
![Screenshot_20240613-205016](https://github.com/monlor/docker-xiaoya/assets/25220944/6da44e5f-f3d9-40c8-83d5-88c88636c65e)

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
在此添加有关问题的任何其他上下文。

---

**Comment by monlor** [comment]
光媒体数据就有50多G，很正常的，让他自己慢慢扫就行了，时间取决于你的cpu 硬盘 内存性能

**Comment by kqkq** [comment]
@monlor 请问想要每日更新的话，要每天手动点一下这个”扫码媒体库文件“吗？Alist似乎是每天都有更新的，Emby似乎从来没更新过，至少几个”每日更新“分类看起来不是每日更新的。

**Comment by monlor** [comment]
> @monlor 请问想要每日更新的话，要每天手动点一下这个”扫码媒体库文件“吗？Alist似乎是每天都有更新的，Emby似乎从来没更新过，至少几个”每日更新“分类看起来不是每日更新的。

emby可以自己设置自动扫描
