### ISSUE TITLE
Truenas Scale Custom App metadata 磁盘检测报错

### ISSUE THREAD

**Issue by rpeng6** [monlor/docker-xiaoya#120]
你好 xiaoya alist, 安装成功可是安装metadata后再报错
“2024-06-14 19:43:21.961237+08:00检查alist连通性...
2024-06-14 19:43:21.981432+08:00alist启动完成，等待10秒后开始下载元数据...
2024-06-14 19:43:31.983629+08:00开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
2024-06-14 19:43:31.989875+08:00目录/media/temp最少需要剩余空间：5G，目前仅剩：0G”
不知道能不能添加一个环境变量可打开或关闭这个检测功能

**Comment by monlor** [comment]
确定是检测错误么？进容器看看空间

**Comment by rpeng6** [comment]
> 确定是检测错误么？进容器看看空间

我是map的一个位置
![image](https://github.com/monlor/docker-xiaoya/assets/87654765/766ebbae-e194-4fb7-bbab-325d4f41238a)
还有14.85TB空间
![image](https://github.com/monlor/docker-xiaoya/assets/87654765/90dd7697-40e0-44f9-a402-7c0f44edd5de)

**Comment by rpeng6** [comment]
> 确定是检测错误么？进容器看看空间
进入容器在报错 “command terminated with exit code 137” log 还是显示
2024-06-15 08:14:29.580011+08:00检查alist连通性...
2024-06-15 08:14:29.588236+08:00alist启动完成，等待10秒后开始下载元数据...
2024-06-15 08:14:39.589696+08:00开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
2024-06-15 08:14:39.595190+08:00目录/media/temp最少需要剩余空间：5G，目前仅剩：0G

**Comment by monlor** [comment]
在容器里执行`df -P /media/temp`看看磁盘空间呢

**Comment by rpeng6** [comment]
> 在容器里执行`df -P /media/temp`看看磁盘空间呢

执行两个指令ls显示结果
![image](https://github.com/monlor/docker-xiaoya/assets/87654765/fbc4e27c-5b9e-424d-b5a3-8550aa520e61)
还有df -P /media/temp
![image](https://github.com/monlor/docker-xiaoya/assets/87654765/ae90118f-79c4-432a-bb31-cb4bea33322b)
容器还在抱空间错误

**Comment by monlor** [comment]
我知道了，你这里多了一个空格，Storage Pool，导致取错值了

**Comment by rpeng6** [comment]
> 我知道了，你这里多了一个空格，Storage Pool，导致取错值了

换了一个地方还是这个问题，是否可以添加环境变量来控制磁盘空间检测功能？
![image](https://github.com/monlor/docker-xiaoya/assets/87654765/e5544080-7386-4f14-9051-a0c12990498d)
