### ISSUE TITLE
增加 xiaoya-tv 支持

### ISSUE THREAD

**Issue by fbigun** [monlor/docker-xiaoya#122]
**您的功能建议是否与某个问题有关？请描述。**
对问题的明确简洁描述。

https://github.com/power721/alist-tvbox
使用xiaoya-tvbox，对nas系统要求更低；

**描述您想要的解决方案**
对您想要发生的事情的明确简洁描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的明确简洁描述。

**其他背景信息**
在此添加任何其他与该功能建议有关的内容或截图。

**Comment by monlor** [comment]
需要的话，自己安装就行了，暂不考虑添加
