### ISSUE TITLE
无法登录小雅alist，网页一篇空白，CSS文件不存在

### ISSUE THREAD

**Issue by TigerIIAusfB** [monlor/docker-xiaoya#123]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
正常使用docker启动alist后，登录网页http://IP:5678，页面一片空白。开启浏览器开发者模式查看相关信息，发现相关样式CSS文件请求失败，如下图
![image](https://github.com/monlor/docker-xiaoya/assets/22821398/04e42de7-4d5b-40cd-a8bd-4f6391f27ee8)
![image](https://github.com/monlor/docker-xiaoya/assets/22821398/523ff6b3-a7de-4323-b422-265acc2d5b24)

**重现步骤**
复现问题的步骤:
1. 正常使用docker启动所有容器
2. 确认服务完全启动
3. 请求小雅alist主页“http://192.168.50.1:5678”
4. 出现错误：“（索引）:154 GET http://192.168.50.1:5678/assets/index.15d8d646.css net::ERR_EMPTY_RESPONSE”、“（索引）:154 
 GET http://192.168.50.1:5678/assets/index.e234f7b7.js net::ERR_EMPTY_RESPONSE”

**预期行为**
成功登录小雅主页，看到相关元数据列表

**截图**
截图请看上面

**设备 (请填写以下信息):**
 - [ ] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [x] 其他（在下面填写）
 - [x]  openwrt
 
**其他信息**
经过多方查询，可能是alist的cdn设置问题，但我不知道如何处理，还请大佬帮忙确认一下

---

**常见问题**

如果你的问题不在此列表中，仍然需要提问，请删除**常见问题**这块内容再提交问题

* 获取file id失败：1. 请检查你的阿里云盘token，opentoken和folderid配置是否正确，2. 阿里云盘空间是否饱和，3. 多次尝试更换token和opentoken。

**Comment by monlor** [comment]
看不出来，检查alist日志

**Comment by TigerIIAusfB** [comment]
> 看不出来，检查alist日志

alist日志没有报错
![image](https://github.com/monlor/docker-xiaoya/assets/22821398/9dfb3f45-6c42-4050-8d60-5ea1d9f4c1e1)

但是nginx上报错无权限
![image](https://github.com/monlor/docker-xiaoya/assets/22821398/45cc74a6-4455-43c3-9214-66c1ce49d6a7)

**Comment by monlor** [comment]
映射目录权限分配一下试试

**Comment by TigerIIAusfB** [comment]
> 映射目录权限分配一下试试

![image](https://github.com/monlor/docker-xiaoya/assets/22821398/fd640da2-8222-442b-a023-fe722cf8ce39)
就很奇怪，原本权限是对的，我改成777还是不行

**Comment by lonuo** [comment]
alist | http://ip:5678 | -

小雅alist 的后台账户密码是啥？为啥登录不了

**Comment by TigerIIAusfB** [comment]
> alist | http://ip:5678 | -
> 
> 小雅alist 的后台账户密码是啥？为啥登录不了

用户名和密码都是默认的，登录不了的原因上面也具体写了，目前根本到不了登录界面，网页都打不开

**Comment by TigerIIAusfB** [comment]
> 映射目录权限分配一下试试

大佬，弄好了。修改目录权限没用，修改nginx的启动用户为root后就可以
![image](https://github.com/monlor/docker-xiaoya/assets/22821398/6faaa5e6-ce89-4e7e-aec4-158f0fe4ef47)

但是就感觉非常奇怪，其他人部署的好像都没有遇到这种奇怪的问题，就我这个有问题，感觉是还是操作系统上有点啥问题吧，具体的不纠结了，谢谢大佬指点

**Comment by monlor** [comment]
确实没见过这个问题
