### ISSUE TITLE
好菜，不知道emby的密码

### ISSUE THREAD

**Issue by haozhengeng** [monlor/docker-xiaoya#124]
![image](https://github.com/monlor/docker-xiaoya/assets/26107251/66e4dfe6-a1f3-44c1-8b05-1a694413285c)
真的觉得自己好菜

**Comment by haozhengeng** [comment]
知道了，小雅的的是1234，好菜啊

**Comment by szsong** [comment]
jellyfin 的用户名密码是啥，monlor老大没写啊，挠头

**Comment by monlor** [comment]
> jellyfin 的用户名密码是啥，monlor老大没写啊，挠头
> 
> 
> 
> 。。。。找到了，在install.sh里面有写。。。
> 
> 
> 
> 可是像我这种用dockercompose 部署的哪里会看到这个啊

原来有人直接用配置文件，我下次把账号密码都写上吧🤣

**Comment by szsong** [comment]
感谢Monlor老大！
如果要写的话，顺便把安全提示也加一下，有映射外网的朋友，一定记得改密码

**Comment by monlor** [comment]
> 感谢Monlor老大！ 如果要写的话，顺便把安全提示也加一下，有映射外网的朋友，一定记得改密码

这个写了

**Comment by lzjqsdd** [comment]
> > jellyfin 的用户名密码是啥，monlor老大没写啊，挠头
> > 。。。。找到了，在install.sh里面有写。。。
> > 可是像我这种用dockercompose 部署的哪里会看到这个啊
> 
> 原来有人直接用配置文件，我下次把账号密码都写上吧🤣

我也用的 docker compose部署的(alist+emby方案)，试了xiaoya的1234密码也不对
