### ISSUE TITLE
下载元数据失败

### ISSUE THREAD

**Issue by cslhky** [monlor/docker-xiaoya#126]
iaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:07 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | ======+====+===========+=======================================================
xiaoya-metadata-1  | 0d43aa|OK  |   1.6KiB/s|/media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 2...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:17 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:17 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | ======+====+===========+=======================================================
xiaoya-metadata-1  | e0c57c|OK  |   1.6KiB/s|/media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 3...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:27 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:27 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.

**Comment by cslhky** [comment]
xiaoya-metadata-1  | alist启动完成，等待10秒后开始下载元数据...
xiaoya-jellyfin-1  | 等待配置数据下载完成...
xiaoya-metadata-1  | 开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
xiaoya-metadata-1  | Downloading Jellyfin config...
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4...
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 1...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:12:59 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:12:59 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 2...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:09 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:09 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 3...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:19 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:19 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 4...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:29 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:29 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 5...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:39 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:13:40 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed.
xiaoya-metadata-1 exited with code 1
xiaoya-metadata-1  | 开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
xiaoya-metadata-1  | Downloading Jellyfin config...
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4...
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 1...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:07 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:07 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | ======+====+===========+=======================================================
xiaoya-metadata-1  | 0d43aa|OK  |   1.6KiB/s|/media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 2...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:17 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:17 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | ======+====+===========+=======================================================
xiaoya-metadata-1  | e0c57c|OK  |   1.6KiB/s|/media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 3...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:27 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:27 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 4...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:37 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:38 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Downloading Jellyfin/config_jf.mp4, try 5...
xiaoya-metadata-1  | Link is http://alist:5678/d/元数据/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:48 [NOTICE] Downloading 1 item(s)
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-metadata-1  | 
xiaoya-metadata-1  | 06/16 15:14:48 [NOTICE] Download complete: /media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Download Results:
xiaoya-metadata-1  | gid   |stat|avg speed  |path/URI
xiaoya-metadata-1  | ======+====+===========+=======================================================
xiaoya-metadata-1  | ac84c3|OK  |   1.5KiB/s|/media/temp/Jellyfin/config_jf.mp4
xiaoya-metadata-1  | 
xiaoya-metadata-1  | Status Legend:
xiaoya-metadata-1  | (OK):download completed.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
xiaoya-metadata-1  | Download Jellyfin/config_jf.mp4 failed.
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found
xiaoya-alist-1     | 获取目录失败： object not found

**Comment by monlor** [comment]
不清楚什么原因，加载jellyfin元数据分享没成功

**Comment by zjw57369** [comment]
解决了么
