### ISSUE TITLE
请把环境变量里增加一个代理选项，V1.0.1是安装完下载完元数据后手动给配置文件夹添加proxy.txt来开通代理pikpak

### ISSUE THREAD

**Issue by CoOlaRlL** [monlor/docker-xiaoya#130]
**您的功能建议是否与某个问题有关？请描述。**
请把环境变量里增加一个代理选项，V1.0.1是安装完下载完元数据后手动给配置文件夹添加proxy.txt来开通代理pikpak

**描述您想要的解决方案**
在EV文件中增加代理选项，更优雅的使用小雅pikpak~

**Comment by monlor** [comment]
有这个选项：https://github.com/monlor/docker-xiaoya/tree/main/alist
