### ISSUE TITLE
镜像运行中出错

### ISSUE THREAD

**Issue by cchen998** [monlor/docker-xiaoya#134]
![图片_20240618162315](https://github.com/monlor/docker-xiaoya/assets/132991404/aade23c4-c829-463c-a31d-eb1743cb3104)

**Comment by cchen998** [comment]
我发现应该是config.mp4的路径不对，里面没有目录/D/？但是不知道在哪里修改。

**Comment by monlor** [comment]
检查alist

**Comment by cchen998** [comment]
![Snipaste_2024-06-18_17-12-29](https://github.com/monlor/docker-xiaoya/assets/132991404/e33962c2-d9df-4bea-99a7-83f3ab02b628)
dalao大佬，具体是检查alist哪个地方的配置？

**Comment by cchen998** [comment]
应该是路径的问题，但是我找不到在哪里修改路径？

**Comment by cchen998** [comment]
alist    failed get enabled storages: TokenVerifyFailed:The token was expected to have 3 parts, but got 1.  这个错误？

**Comment by monlor** [comment]
这个问题，我这边没办法处理，只能自己尝试

**Comment by swibignw** [comment]
下载数据量大，出错时可以停了，再重新开始就好了。
