### ISSUE TITLE
是否可以增加xiaoya的open-api支持？现在是否支持？

### ISSUE THREAD

**Issue by mefengyang** [monlor/docker-xiaoya#138]

**Comment by monlor** [comment]
有相关资料么，不清楚指的是什么

**Comment by mefengyang** [comment]
https://t.me/xiaoya_doc/16

**Comment by mefengyang** [comment]
如何申请和配置open api？

1、去 https://www.aliyundrive.com/developer/f   
申请开发者权限，理由自己想办法编，我让gpt帮忙编的。

2、得到授权后在 https://www.aliyundrive.com/developer/f
新建一个app，三个权限都要同意（我就在这步卡了半天）。授权回调uri填
https://alist.nn.ci/tool/aliyundrive/request.html
https://openapi.alipan.com/oauth/access_token

3、获取自己的app id和App Secret后在open_api.txt中按这个格式填
https://openapi.alipan.com/oauth/access_token（空格）app_id（空格）app_secret

4、访问 https://alist.nn.ci/tool/aliyundrive/request.html 中选 use my own client，输入自己的app id和App Secret，用登入方式而不是扫码方式，重新获取自己的opentoken，替换进myopentoken.txt中。

5、重启小雅docker

**Comment by monlor** [comment]
这个不用我支持啊，你获取到opentoken，部署的时候填进来就行了

**Comment by YUAN121300** [comment]
部署完怎么修改opentoken 折腾半天没弄明白

**Comment by monlor** [comment]
> 部署完怎么修改opentoken 折腾半天没弄明白

重新执行安装脚本
