### ISSUE TITLE
读取元数据时报错

### ISSUE THREAD

**Issue by cchen998** [monlor/docker-xiaoya#140]
06/19 20:50:03 [NOTICE] Downloading 1 item(s)

06/19 20:50:03 [NOTICE] CUID#7 - Redirecting to http://img.xiaoya.pro/abnormal.png

06/19 20:50:04 [ERROR] CUID#7 - Download aborted. URI=http://alist:5678/d/%E5%85%83%E6%95%B0%E6%8D%AE/config.mp4
Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://img.xiaoya.pro/abnormal.png
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

06/19 20:50:04 [NOTICE] Download GID#89bea4f95a7b7c6b not complete: /media/temp/config.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
89bea4|ERR |       0B/s|/media/temp/config.mp4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Downloading config.mp4, try 4...
Link is http://alist:5678/d/元数据/config.mp4

06/19 20:50:04 [NOTICE] Downloading 1 item(s)

06/19 20:50:04 [NOTICE] CUID#7 - Redirecting to http://img.xiaoya.pro/abnormal.png

06/19 20:50:05 [ERROR] CUID#7 - Download aborted. URI=http://alist:5678/d/%E5%85%83%E6%95%B0%E6%8D%AE/config.mp4
Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://img.xiaoya.pro/abnormal.png
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

06/19 20:50:05 [NOTICE] Download GID#a876e50357d4bc9d not complete: /media/temp/config.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
a876e5|ERR |       0B/s|/media/temp/config.mp4

兜兜转转一天了，又到这个地方了，昨天UP主提示检查Alist，找不到方向。
http://alist:5678/d/元数据/config.mp4  进去Alist查看没有这个目录，这个下载地址带上  /D的目录？
请大佬指点。

**Comment by swibignw** [comment]
和我一样，直接说没数据

**Comment by swibignw** [comment]
日志初始化存储出错。

**Comment by monlor** [comment]
就是alist部署有问题，检查alist配置，检查阿里云盘账号，我没有处理办法
