### ISSUE TITLE
jellyfin docker-compose.yaml文件怎么开启硬解

### ISSUE THREAD

**Issue by chrinly** [monlor/docker-xiaoya#144]
如题，求解答

**Comment by szsong** [comment]
首先，个人理解，你如果使用xiaoya，那么开启硬解没有太大意义，除非你的容器所在的服务器的下载带宽远高于你的客户端的下载带宽。（比如你用手机流量看 jellyfin）只有在这种情况下硬解转码才有意义（节约客户端带宽）

其次，你的问题不是这个repo方案特有的，所以网上有很多jellyfin开启硬解的教程，请善用搜索
