### ISSUE TITLE
alist容器内部时间不是北京时间，自动清理设置半个月清理一次，实际好像1小时就被清理了

### ISSUE THREAD

**Issue by hanlihanshaobo** [monlor/docker-xiaoya#145]

**Comment by monlor** [comment]
设置之后有没有reload，怎么设置的

**Comment by hanlihanshaobo** [comment]
> 设置之后有没有reload，怎么设置的

重启吗，我重启了，还是不行，删除重装了也是
# 自动清理阿里云盘
AUTO_CLEAR_ENABLED=true
# 阿里云盘自动清理间隔，单位分钟，默认10分钟
AUTO_CLEAR_INTERVAL=20160

**Comment by monlor** [comment]
> > 设置之后有没有reload，怎么设置的
> 
> 
> 
> 重启吗，我重启了，还是不行，删除重装了也是
> 
> #自动清理阿里云盘
> 
> AUTO_CLEAR_ENABLED=true
> 
> #阿里云盘自动清理间隔，单位分钟，默认10分钟
> 
> AUTO_CLEAR_INTERVAL=20160

没看安装提示吧，修改环境变量要reload，重启不行

**Comment by hanlihanshaobo** [comment]
> > > 设置之后有没有reload，怎么设置的
> > 
> > 
> > 重启吗，我重启了，还是不行，删除重装了也是
> > #自动清理阿里云盘
> > AUTO_CLEAR_ENABLED=真
> > #阿里云盘自动清理间隔，单位分钟，默认10分钟
> > AUTO_CLEAR_INTERVAL=20160
> 
> 没看安装提示吧，修改环境变量要重新加载，重启不行

docker compose up -d  ?这个我做了， 我是直接环境变量文件填好之后再部署服务的

**Comment by monlor** [comment]
哦哦，那应该没问题，进alist容器看看定时任务，crontab -l

**Comment by hanlihanshaobo** [comment]
> 哦哦，那应该没问题，进alist容器看看定时任务，crontab -l

*/20160 * * * * ,应该是定时任务的问题，还有容器内部的时间也不是北京时间，差8小时

**Comment by monlor** [comment]
容器内时区不对也不会影响定时任务的周期，这看着是没问题的

**Comment by hanlihanshaobo** [comment]
> 容器内时区不对也不会影响定时任务的周期，这看着是没问题的

这个定时任务应该是按分钟设定的，不能设置超过60分钟，超过了也是按60分钟清理一次，不知道我理解的对不对。容器内部时间是另一个问题，也不是啥重要问题

**Comment by monlor** [comment]
我看了下，确实是的，你需要超过60分钟是基于什么原因呢

**Comment by hanlihanshaobo** [comment]
> 我看了下，确实是的，你需要超过60分钟是基于什么原因呢

没啥用，开会员了，就想存多点再清理😂，没必要清理那么快

**Comment by monlor** [comment]
总不能搞成crontab的格式吧，就这样吧，解析成小时 天也费劲
