### ISSUE TITLE
小雅支持夸克网盘，可以支持一下吗？

### ISSUE THREAD

**Issue by geekdmm0xff** [monlor/docker-xiaoya#146]
![image](https://github.com/monlor/docker-xiaoya/assets/10804912/93c01510-7681-496c-bb78-657854bee792)

**您的功能建议是否与某个问题有关？请描述。**
对问题的明确简洁描述。

**描述您想要的解决方案**
对您想要发生的事情的明确简洁描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的明确简洁描述。

**其他背景信息**
在此添加任何其他与该功能建议有关的内容或截图。

**Comment by monlor** [comment]
已经支持了

**Comment by virtually321** [comment]
必须分享吗？就想把夸克账号挂上去咋弄？
