### ISSUE TITLE
如何自动更新 alist， 或者说如何自动更新 xiaoyaliu/alist 这个基础镜像？

### ISSUE THREAD

**Issue by paranoiagu** [monlor/docker-xiaoya#149]
我用xiaoyaliu/alist的时候，是直接每天拉取新版本、重启。

现在 monlor/xiaoya-alist 是在 xiaoyaliu/alist 基础上封的镜像，那么如何能在 xiaoyaliu/alist 更新后，获取到新的版本？

**Comment by monlor** [comment]
不行，可以自己fork
