### ISSUE TITLE
jellyfin打不开

### ISSUE THREAD

**Issue by lorna665** [monlor/docker-xiaoya#15]
部署环境：debian11，防火墙已关闭。
部署方式：一键脚本
部署方案：alist+emby+jellyfin

访问IP+6908可以正常打开emby。
IP+8096端口无法打开jellyfin

**Comment by wsppiup** [comment]
你好，请问默认账号密码多少？

**Comment by monlor** [comment]
> 你好，请问默认账号密码多少？

试试 xiaoya/1234

**Comment by monlor** [comment]
之前的jellyfin部署有问题，之前部署过的建议完全卸载之后重装新版本，新版本已经适配

**Comment by RangeZero** [comment]
> > 你好，请问默认账号密码多少？
> 
> 试试 xiaoya/1234

这个账号密码登陆失败，请问去哪查看账号密码？

**Comment by monlor** [comment]
> > > 你好，请问默认账号密码多少？
> 
> > 
> 
> > 试试 xiaoya/1234
> 
> 
> 
> 这个账号密码登陆失败，请问去哪查看账号密码？

安装完就有提示啊
