### ISSUE TITLE
can't open '/tmp/status'

### ISSUE THREAD

**Issue by akakClavin** [monlor/docker-xiaoya#150]
试了很多次脚本，为什么每次都是这个报错can't open '/tmp/status'，到底是什么问题啊·

**Comment by monlor** [comment]
提供完整日志

**Comment by Rokuha233** [comment]
同样的问题，无论重新部署多少次都是一样的结果，下面是完整日志
开始生成配置文件...
添加阿里云盘 Token...
添加阿里云盘 Open Token...
添加阿里云盘 Folder ID...
添加夸克网盘 Cookie...
已关闭TVBOX安全模式...
启动定时更新定时任务...
启动定时清理定时任务...
开始自动更新媒体服务地址...
等待emby.js创建完成...
有效地址为：https://gitlab.com/xiaoyaliu/data/-/raw/main
最新版本 0.10.27 开始更新下载.....

成功更新 tvbox.zip
成功更新 update.zip
等待jellyfin.js创建完成...
成功更新 index.zip
成功更新 version.txt
/data/pikpak.txt: No such file or directory (os error 2)
167 records have been updated into your database
Thu Jul 11 04:26:08 CST 2024 update index succesfully, your new version.txt is 0.10.27
Thu Jul 11 04:26:08 CST 2024 User's own token 13a9947032424e768d3ab6124a705a68 has been updated into database successfully
cat: can't open '/tmp/status': No such file or directory
cat: can't open '/tmp/status': No such file or directory
cat: can't open '/tmp/status': No such file or directory
