### ISSUE TITLE
[FEATURE]: Helm部署文档

### ISSUE THREAD

**Issue by Jas0n0ss** [monlor/docker-xiaoya#154]
### 功能建议的描述

兄弟，我看你最近更新了helm，就想着没有再开一个guide，把这一套部署到k8s机群里面去，docker和docker-compose对于新手来讲都不是太大问题，如果有k8s 部署的教程就更好了，弹性伸缩，扩容，高可用什么的都解决了，直接可以上生产了

### 优先级

非常高

**Comment by monlor** [comment]
可以啊，之前感觉受众比较少就没写

**Comment by Jas0n0ss** [comment]
> 可以啊，之前感觉受众比较少就没写

太感谢了大兄弟
