### ISSUE TITLE
[BUG]:用vidhub或者fileball连接emby，不能保存播放记录，或者保存了播放记录不能保存进度

### ISSUE THREAD

**Issue by howpic** [monlor/docker-xiaoya#159]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [ ] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [ ] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

不知道是啥问题，是否可排查一下，谢谢

### 设备 (请填写以下信息)

Mac

**Comment by monlor** [comment]
用2345可能有这个问题，试试6908

**Comment by howpic** [comment]
感谢回复，如何更改端口呢？重新运行脚本？

**Comment by howpic** [comment]
感谢
