### ISSUE TITLE
需要提升阿里云盘自动清理间隔时间最大60分钟设置

### ISSUE THREAD

**Issue by LINJIAXIN-China** [monlor/docker-xiaoya#171]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

有尝试将阿里云盘自动清理间隔时间设定300分钟，结果实际生效为60分钟，当使用小雅播放电影时，到达触发阿里云盘自动清理时间时，将阿里云盘文件清理后，电影会卡住无法播放，需要重新刷新使小雅重新将电影转存至中转盘方可继续播放。建议提升设定上限，谢谢。

### 重现步骤

1、首次使用小雅播放视频时，视频频繁卡住无法正常播放，需要刷新后可解决，查看日志同一时间节点有触发清理阿里云盘记录，尝试将清理时间间隔放大，发现视频卡住无法播放与此有强相关性。
2、当出现视频卡住无法正常播放时，偶尔会出现刷新无法解决，查看日志中无重新将视频转存至阿里云盘，重启小雅容器可解决，解决后查看日志中有将视频转存至阿里云盘记录，更加确定视频卡住无法播放为阿里云盘视频文件被清理。
以上bug，望作者协助优化阿里云盘自动清理间隔上限60分钟设定可改善，谢谢。

### 设备 (请填写以下信息)

绿联

**Comment by wjkjinke00** [comment]
通过修改启动文件start.sh,将定时启动clear的任务改为每3小时执行一次,观察发现还是有卡顿的现象.而且阿里云盘确实有两个相同的资源,文件名后面有1.
通过以上判断,应该不是定时清除造成.或许还有其他bug

**Comment by monlor** [comment]
我记得设置1分钟都不会播放卡住么？是偶发还是必现

**Comment by LINJIAXIN-China** [comment]
是比现，一开始默认是10分钟，看到20分钟就卡住无法继续播放，出现了好几次，有找到这个自动清理云盘有两个默认10分钟，怀疑为这个的影响，查看env只有一个可以设定，修改为300后，就变成60分钟了，晚上我可以在测试下把日志截出来，之前测试的时候，因为修改env文件需要重启，重启后之前的日志都没了

**Comment by LINJIAXIN-China** [comment]
是比现，一开始默认是10分钟，看到20分钟就卡住无法继续播放，出现了好几次，有找到这个自动清理云盘有两个默认10分钟，怀疑为这个的影响，查看env只有一个可以设定，修改为300后，就变成60分钟就卡住无法播放了，晚上我可以在测试下把日志截出来，之前测试的时候，因为修改env文件需要重启，重启后之前的日志都没了

**Comment by LINJIAXIN-China** [comment]
alist-1     | 07-04-2024 09:35:49 新增转存记录, 挂载路径:  /电影/中国  文件:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 文件:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv   新增下载直链:  https://cn-beijing-data.aliyundrive.net/0slkNM9g%2F16671620%2F605a91e41d0f9ac821524abfbf889063a3577509%2F605a91e471eea114008d4b0a8b18833927b810a1?callback=eyJjYWxsYmFja1VybCI6Imh0dHA6Ly9iajI5LmFwaS1ocC5hbGl5dW5wZHMuY29tL3YyL2ZpbGUvZG93bmxvYWRfY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJodHRwSGVhZGVyLnJhbmdlPSR7aHR0cEhlYWRlci5yYW5nZX1cdTAwMjZidWNrZXQ9JHtidWNrZXR9XHUwMDI2b2JqZWN0PSR7b2JqZWN0fVx1MDAyNmRvbWFpbl9pZD0ke3g6ZG9tYWluX2lkfVx1MDAyNnVzZXJfaWQ9JHt4OnVzZXJfaWR9XHUwMDI2ZHJpdmVfaWQ9JHt4OmRyaXZlX2lkfVx1MDAyNmZpbGVfaWQ9JHt4OmZpbGVfaWR9XHUwMDI2cGRzX3BhcmFtcz0ke3g6cGRzX3BhcmFtc31cdTAwMjZ2ZXJzaW9uPSR7eDp2ZXJzaW9ufSIsImNhbGxiYWNrQm9keVR5cGUiOiJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQiLCJjYWxsYmFja1N0YWdlIjoiYmVmb3JlLWV4ZWN1dGUiLCJjYWxsYmFja0ZhaWx1cmVBY3Rpb24iOiJpZ25vcmUifQ%3D%3D&callback-var=eyJ4OmRvbWFpbl9pZCI6ImJqMjkiLCJ4OnVzZXJfaWQiOiIzOWYyYjk5YzYzYTA0MjUyYTdmNGM3NTZjYjc0MDc5MCIsIng6ZHJpdmVfaWQiOiI3NjU1NzM1NTMiLCJ4OmZpbGVfaWQiOiI2Njg2NmNmNDhkNDdkM2JhNDc4ODRlMDQ4ODE0YjkwOGFhMjAzOTdjIiwieDpwZHNfcGFyYW1zIjoie1wiYXBcIjpcIjc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmXCJ9IiwieDp2ZXJzaW9uIjoidjMifQ%3D%3D&di=bj29&dr=765573553&f=66866cf48d47d3ba47884e048814b908aa20397c&pds-params=%7B%22ap%22%3A%2276917ccccd4441c39457a04f6084fb2f%22%7D&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%25B5%258C%25E7%25A5%259E.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv&security-token=CAISvgJ1q6Ft5B2yfSjIr5aCLOzzvKdO2avTOnz7o1EMNetkvpTmqTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXqXOF63q1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg7VM1nu%2Bi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iljtPpvXtuMkagAGIuKQYlKb1WJr9UfRbrS%2FT9jSbAyGcWFMwaY3kc9zZtMz%2B1Go3tRiBXENTueEUR1dG4xOj5T3TTRsFjM8%2BBGIaHMfEDIB2Er%2BHb0aHaXw1%2FgR3fOKUg2Md8YwNDfAoFyTqiNWv73cxvpqp61ycOLu%2BhONybi75dWssEom4yny5HiAA&u=39f2b99c63a04252a7f4c756cb740790&x-oss-access-key-id=STS.NU7gVGQxoni88ZJGQY9dHQQMK&x-oss-expires=1720100051&x-oss-signature=ELUypyVHim6894CJRsLbqcz%2BdR23J31fAnxSYydntqM%3D&x-oss-signature-version=OSS2
alist-1     | 07-04-2024 09:35:52  已成功缓存了 1 个文件
alist-1     | 07-04-2024 09:35:52 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 09:45:24  清空缓存下载链接:  /电影/中国
alist-1     | 07-04-2024 09:48:53 新增转存记录, 挂载路径:  /电影/中国  文件:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     |
alist-1     | [2024/07/04 10:00:01]开始清理小雅alist转存
alist-1     | 彻底删除文件：/资源盘/来自分享/小雅转存文件夹/赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT(1).mkv
alist-1     | 彻底删除文件：/资源盘/来自分享/小雅转存文件夹/赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 10:01:53 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 10:06:57 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 1 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 2 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 10:07:02 获取转存后的直链失败！！！ NotFound.File:The resource file cannot be found. file not exist
alist-1     | 07-04-2024 10:07:02 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取目录失败： object not found
alist-1     | 07-04-2024 10:07:20 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 1 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 2 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 10:07:25 获取转存后的直链失败！！！ NotFound.File:The resource file cannot be found. file not exist
alist-1     | 07-04-2024 10:07:25 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取目录失败： object not found
alist-1     | 07-04-2024 10:07:45 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 1 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 获取下载链接失败第 2 次  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv
alist-1     | 07-04-2024 10:07:49 获取转存后的直链失败！！！ NotFound.File:The resource file cannot be found. file not exist
alist-1     | 07-04-2024 10:07:49 文件已转存:  赌神.God.of.Gamblers.1989.DVDRip.x264.AC3.2Audios-CMCT.mkv


日志如上，我17:30左右开始播放，到18:00时日志显示清理小雅alist转存，查看网页视频进度条有多缓存一小部分，到18:03开始视频卡住无法正常播放，本次尝试刷新无法恢复播放，重启容器即可，下面为录制的视频（还没重启容器）
https://github.com/monlor/docker-xiaoya/assets/83872506/d66d6cc3-efb4-4fb7-a416-34390df6f330

**Comment by xingtong00** [comment]
有个问题，为啥env里不直接使用cron呢？反正都是通过crontab来进行清理的。

**Comment by monlor** [comment]
> 有个问题，为啥env里不直接使用cron呢？反正都是通过crontab来进行清理的。

方便小白用户，如果真的清理过快导致无法播放，单位用小时就好了

**Comment by LINJIAXIN-China** [comment]
> > 有个问题，为啥env里不直接使用cron呢？反正都是通过crontab来进行清理的。
> 
> 方便小白用户，如果真的清理过快导致无法播放，单位用小时就好了

是否可以尝试将单位更改为小时，然后我再测试看下还会不会出现此bug？

**Comment by monlor** [comment]
#173 已经有pr修复了，还没发版本

**Comment by monlor** [comment]
已发布
