### ISSUE TITLE
[BUG]: 获取目录失败： object not found

### ISSUE THREAD

**Issue by hxng1006** [monlor/docker-xiaoya#176]
### 提交检查

- [ ] 我已经搜索过 Issues，没有找到类似问题
- [ ] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [ ] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

callback=eyJjYWxsYmFja1VybCI6Imh0dHA6Ly9iajI5LmFwaS1ocC5hbGl5dW5wZHMuY29tL3YyL2ZpbGUvZG93bmxvYWRfY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJodHRwSGVhZGVyLnJhbmdlPSR7aHR0cEhlYWRlci5yYW5nZX1cdTAwMjZidWNrZXQ9JHtidWNrZXR9XHUwMDI2b2JqZWN0PSR7b2JqZWN0fVx1MDAyNmRvbWFpbl9pZD0ke3g6ZG9tYWluX2lkfVx1MDAyNnVzZXJfaWQ9JHt4OnVzZXJfaWR9XHUwMDI2ZHJpdmVfaWQ9JHt4OmRyaXZlX2lkfVx1MDAyNmZpbGVfaWQ9JHt4OmZpbGVfaWR9XHUwMDI2cGRzX3BhcmFtcz0ke3g6cGRzX3BhcmFtc31cdTAwMjZ2ZXJzaW9uPSR7eDp2ZXJzaW9ufSIsImNhbGxiYWNrQm9keVR5cGUiOiJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQiLCJjYWxsYmFja1N0YWdlIjoiYmVmb3JlLWV4ZWN1dGUiLCJjYWxsYmFja0ZhaWx1cmVBY3Rpb24iOiJpZ25vcmUifQ%3D%3D&callback-var=eyJ4OmRvbWFpbl9pZCI6ImJqMjkiLCJ4OnVzZXJfaWQiOiJjNzliZjAwNjA4ZjE0ZmM1YmVkOWRhZjE5OGY1YzI2YyIsIng6ZHJpdmVfaWQiOiI2MzQwODA4NzIiLCJ4OmZpbGVfaWQiOiI2Njg3ZTFmNjdlZjQ2OWJlM2Y1NDQxMDY4NzAzMTg1OGYxMTBiNzYyIiwieDpwZHNfcGFyYW1zIjoie1wiYXBcIjpcIjc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmXCJ9IiwieDp2ZXJzaW9uIjoidjMifQ%3D%3D&di=bj29&dr=634080872&f=6687e1f67ef469be3f54410687031858f110b762&pds-params=%7B%22ap%22%3A%2276917ccccd4441c39457a04f6084fb2f%22%7D&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%2733.mkv&security-token=CAISvgJ1q6Ft5B2yfSjIr5f7KN3xmL5vzoelV0HfvTcDZ9wVv6v%2F1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUejQC63q1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ%2F5L7XzGi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iSZKCrfXtuMkagAFq0RTi6DTBUnwD6OlK7i8miXGOlIEwLtqf7WctK8cgefDrlWXQYHJk7gcCPoEK4ZiOpkQfo9C8TfNMoLvyPaNketpVlBHxVtRLrjwoomQyzT%2FBZZMn4qP8lSXd7MEFnTARrXxuctxitAhqXWthCYhmdcPCM1ap1W1WGhlp3x02nSAA&u=c79bf00608f14fc5bed9daf198f5c26c&x-oss-access-key-id=STS.NTNcgEuaNyENUgnY7VkS9PnT5&x-oss-expires=1720195540&x-oss-signature=oYVScmRpA6kpeA%2BXpXKMv%2Fu83%2ByzYjfjoZPKKYrvaFY%3D&x-oss-signature-version=OSS2
407-05-2024 12:07:21  已成功缓存了 2 个文件
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
'获取目录失败： object not found
H07-05-2024 12:13:18 文件已转存并且下载直链已缓存:  33.mkv
H07-05-2024 12:16:37  清空缓存下载链接:  /每日更新/电视剧

3[2024/07/05 12:20:02]开始清理小雅alist转存
=彻底删除文件：/资源盘/小雅转存文件夹/33.mkv
=彻底删除文件：/资源盘/小雅转存文件夹/29.mkv

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
这个错也不代表无法播放，有什么问题么
