### ISSUE TITLE
[FEATURE]: 标准化环境变量的使用

### ISSUE THREAD

**Issue by uwang** [monlor/docker-xiaoya#182]
### 功能建议的描述

在env_file中定义的环境变量，应该在服务配置中通过 ${VARIABLE_NAME} 的方式引用。

### 预期的收益

兼容性更好

### 优先级

低

**Comment by monlor** [comment]
啥意思？compose 支持使用外部env的环境变量，在引用一次不是多余么

**Comment by uwang** [comment]
![image](https://github.com/monlor/docker-xiaoya/assets/9262286/35381e44-0261-420c-bdc6-54057ca4b277)

我的环境里，env 的配置不会生效，只有额外再加 environment 配置才能注入变量

**Comment by uwang** [comment]
![image](https://github.com/monlor/docker-xiaoya/assets/9262286/daa39009-1b9c-415f-aeb2-16e54a8206cd)

**Comment by uwang** [comment]
![image](https://github.com/monlor/docker-xiaoya/assets/9262286/eac5002b-f625-4750-8276-4eb0fd71ec56)

**Comment by monlor** [comment]
chatgpt说env_file的功能是docker compose 1.5版本引入的，建议更新到新版本
