### ISSUE TITLE
[BUG]: sed: can't move 'envhPjHif' to 'env': File exists

### ISSUE THREAD

**Issue by SoledadWang1206** [monlor/docker-xiaoya#188]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

部署类型：
1. alist + emby (默认)
2. alist
3. alist + jellyfin
4. alist + emby + jellyfin
请选择部署服务类型: 1
开始生成配置文件docker-compose.yml...
 -#O=-#    #       #
 -=#=-  #     #        #
sed: can't move 'envhPjHif' to 'env': File exists

出现这个提示怎么解决？

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
sed运行不了，手动部署吧
