### ISSUE TITLE
[BUG]: 观看记录不同步不更新

### ISSUE THREAD

**Issue by jinlin-teck** [monlor/docker-xiaoya#199]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

首先感谢大佬！
我搭建了emby服务，其他功能都正常，就有一个问题就是播放记录也就是`继续观看`不同步，也不更新，如何解决呢？
感谢！

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
用6908端口可以同步

**Comment by jinlin-teck** [comment]
6908也不行啊，两个都试过。

**Comment by monlor** [comment]
如果6908也不行，那我也没有办法，不清楚什么原因

**Comment by jinlin-teck** [comment]
更新汇报一下，目前看到音乐/演唱会下的节目是同步生效的，2345和6908都可以。

**Comment by siben168** [comment]
我也用不了，我是“播放记录”和“最爱”2 个地方都不更新，可以添加最爱的影片，但是删除不了。
换了 6908 端口也不行。 播放记录曾经通过 删除 “library.db-wal” 短暂好过一段时间， 后来又不行 了。
已经决定放弃了，花了好多时间。 -_-
