### ISSUE TITLE
Docker for win: 老大，能否出一个这个系统的安装方式？

### ISSUE THREAD

**Issue by hxng1006** [monlor/docker-xiaoya#200]
### 功能建议的描述

如题。

### 优先级

低

**Comment by monlor** [comment]
说出来你可能不信，我没有windows设备，如果需要的话，可以搜索docker for windows的使用教程，在参考项目中docker-compose手动部署的教程来部署就行了

**Comment by monlor** [comment]
看见有人写文章介绍了
https://mp.weixin.qq.com/s/knrX2fzYvXEZfREcMU00JA
