### ISSUE TITLE
[FEATURE]: support docker_address_ext.txt

### ISSUE THREAD

**Issue by damoye** [monlor/docker-xiaoya#212]
### 功能建议的描述

小雅tvbox支持外网访问，需要配置docker_address_ext.txt，能否支持通过环境变量传入？

### 优先级

中

**Comment by monlor** [comment]
不需要配置，不管内外网都访问`/tvbox/my_ext.json`就行了

**Comment by damoye** [comment]
@monlor 应该要在docker_address_ext.txt里配置域名吧？现在好像没有办法传递域名

**Comment by monlor** [comment]
> @monlor 应该要在docker_address_ext.txt里配置域名吧？现在好像没有办法传递域名

你试过了？截图

**Comment by damoye** [comment]
@monlor 我搞错了，确实可以，多谢

**Comment by monlor** [comment]
我很奇怪，为什么很多人都会问这个问题🤣

**Comment by damoye** [comment]
可能是因为小雅的文档里说外网访问需要配置地址吧
