### ISSUE TITLE
[BUG]: metadata镜像内7zip包配置有问题，导致中文文件名乱码

### ISSUE THREAD

**Issue by RangeZero** [monlor/docker-xiaoya#215]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

元数据解压后中文均为乱码，无法正在运行

### 重现步骤

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (**locale=C,Utf16=off**,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (A70F41),ASM,AES-NI)

### 预期行为

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (**locale=zh_CN,UTF-8,Utf16=ON**,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (A70F41),ASM,AES-NI)

### 日志

```shell
检查alist连通性...
alist启动完成，等待10秒后开始下载元数据...
开始下载元数据，如果有问题无法解决，请删除目录 /media/temp 下的所有文件重新启动.
Downloading Jellyfin config...
Downloading config_jf.mp4...
Found config_jf.mp4, skip.
Extracting Jellyfin config...

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (**locale=C,Utf16=off**,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (A70F41),ASM,AES-NI)

Scanning the drive for archives:
1 file, 5368869413 bytes (5121 MiB)

Extracting archive: temp/config_jf.mp4
--
Path = temp/config_jf.mp4
Type = 7z
Offset = 2821246
Physical Size = 5366048167
Headers Size = 1446182
Method = LZMA2:25
Solid = +
Blocks = 1

ERROR: Can not delete output file : No such file or directory : ./jf_config/root/default/PikPak ????/????.mblink
ERROR: Can not delete output file : No such file or directory : ./jf_config/root/default/PikPak ????/????.mblink
ERROR: Can not delete output file : No such file or directory : ./jf_config/root/default/?? ????/????.mblink

Sub items Errors: 3

Archives with Errors: 1

Sub items Errors: 3
```

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
修复了

**Comment by AnkioTomas** [comment]
> 修复了

@monlor 我拉的最新的镜像测试还是会乱码

`locale-gen zh_CN.UTF-8`没办法正常生成`locale`；

进容器手动用`dpkg-reconfigure locales`重新生成才解决。

好像是`/etc/locale.gen`的问题，还没细细研究~

**Comment by monlor** [comment]
再试一下，我现在没有会员，元数据下载很慢，没法测试

**Comment by RangeZero** [comment]
不试了，我放弃了。
xiaoya能用，但是emby和jellyfin经常出问题看不了，
现在改用tvbox加载链接看了，就这个没出过问题
