### ISSUE TITLE
[BUG]: 安装完成后emby有许多无法播放的影片

### ISSUE THREAD

**Issue by zhsama** [monlor/docker-xiaoya#224]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [ ] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

安装完成后emby有许多无法播放的影片
![image](https://github.com/user-attachments/assets/e913e967-7dbb-4eb1-8110-844b18a144ff)

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
手动刷新元数据

**Comment by AnkioTomas** [comment]
检查logs报错，才能对症下药

**Comment by yefq1984** [comment]
我看到有部分影片不能播放是因为影片是夸克或115的片源（虽然，在配置的时候并没有配置夸克和115的COOKIE）

**Comment by qxj** [comment]
> 我看到有部分影片不能播放是因为影片是夸克或115的片源（虽然，在配置的时候并没有配置夸克和115的COOKIE）

@yefq1984 我也碰到类似的问题，emby日志里看到打开的是115的片源，请问解决了吗? #232

**Comment by poplovetorock** [comment]
手动刷新也显示不了海报。。。

**Comment by zhsama** [comment]
刚配置完需手动重启爬虫同步元数据
