### ISSUE TITLE
[BUG]:   docker exec -it xiaoya-alist-1 bash 进入容器 执行crontab -l 出现两条一样的cron

### ISSUE THREAD

**Issue by waterloo3122** [monlor/docker-xiaoya#234]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [ ] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [ ] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

docker exec -it xiaoya-alist-1 bash 进入容器 执行crontab -l 出现两条一样的cron
```
18 5 * * * /service.sh update
*/10 * * * * /clear.sh
* * * * * /service.sh daemon
*/15 0,15-23 * * * /update_data.sh
0 */2 * * * /check_uc_cookie.sh update
*/15 0,15-23 * * * /update_data.sh
0 */2 * * * /check_uc_cookie.sh update
```

### 设备 (请填写以下信息)

Linux

**Comment by waterloo3122** [comment]
<img width="899" alt="image" src="https://github.com/user-attachments/assets/e2ae9947-08e8-4dc6-9493-763a0fbbd6b0">

**Comment by monlor** [comment]
第四条往下是小雅添加的

**Comment by waterloo3122** [comment]
还发现一个问题 xiaoya-metadata-1这个容器的cron虽然创建成功了，但是并没有执行
复现方法：
exec 进入xiaoya-metadata-1
执行contab -l，可以发现cron正确
```
27 6 */7 * * /emby.sh update
08  12 * * * python3 /solid.py --media /media/xiaoya >> /tmp/solid.py.log 2>&1
```
crontab -e 手动修改cron如下
```
27 6 */7 * * /emby.sh update
08  12 * * * python3 /solid.py --media /media/xiaoya >>xiaoya-metadata-12>&1
```
然后tail -f xiaoya-metadata-1，输出
```
Traceback (most recent call last):
  File "/solid.py", line 8, in <module>
    import aiohttp.client_exceptions
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by monlor** [comment]
> docker-compose方法安装main版本，还发现一个问题 xiaoya-metadata-1这个容器的cron虽然创建成功了，但是并没有执行
> 
> 复现方法：
> 
> exec 进入xiaoya-metadata-1
> 
> 执行contab -l，可以发现cron正确
> 
> ```
> 
> 27 6 */7 * * /emby.sh update
> 
> 08  12 * * * python3 /solid.py --media /media/xiaoya
> 
> ```
> 
> crontab -e 手动修改cron如下
> 
> ```
> 
> 27 6 */7 * * /emby.sh update
> 
> 08  12 * * * python3 /solid.py --media /media/xiaoya  >> /tmp/solid.py.log 2>&1
> 
> ```
> 
> 然后tail -f xiaoya-metadata-1，输出
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/solid.py", line 8, in <module>
> 
>     import aiohttp.client_exceptions
> 
> ModuleNotFoundError: No module named 'aiohttp'
> 
> ```
> 
> exec 进入xiaoya-metadata-1,手动执行python3 /solid.py --media /media/xiaoya是没有问题的

可能是python的lib路径识别有问题，我研究下

**Comment by monlor** [comment]
我测试了下是没问题的么，main版本的metadata服务
<img width="905" alt="image" src="https://github.com/user-attachments/assets/f4f072c5-68aa-4591-a126-4f5eb8e6fb0f">

**Comment by Yaonie-Jie** [comment]
> > docker-compose方法安装main版本，还发现一个问题 xiaoya-metadata-1这个容器的cron虽然创建成功了，但是并没有执行
> > 复现方法：
> > exec 进入xiaoya-metadata-1
> > 执行contab -l，可以发现cron正确
> > ```
> > 
> > 27 6 */7 * * /emby.sh update
> > 
> > 08  12 * * * python3 /solid.py --media /media/xiaoya
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > crontab -e 手动修改cron如下
> > ```
> > 
> > 27 6 */7 * * /emby.sh update
> > 
> > 08  12 * * * python3 /solid.py --media /media/xiaoya  >> /tmp/solid.py.log 2>&1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后tail -f xiaoya-metadata-1，输出
> > ```
> > 
> > Traceback (most recent call last):
> > 
> >   File "/solid.py", line 8, in <module>
> > 
> >     import aiohttp.client_exceptions
> > 
> > ModuleNotFoundError: No module named 'aiohttp'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > exec 进入xiaoya-metadata-1,手动执行python3 /solid.py --media /media/xiaoya是没有问题的
> 
> 可能是python的lib路径识别有问题，我研究下

**Comment by Yaonie-Jie** [comment]
遇到了同样的问题  系统的ARM架构
<img width="627" alt="image" src="https://github.com/user-attachments/assets/5727ce3e-b4f7-41e1-9f37-994114a03e1d">

**Comment by monlor** [comment]
最新main版本已修复
