### ISSUE TITLE
[BUG]: 请问提示获取目录失败是因为什么。。群晖执行的一键安装

### ISSUE THREAD

**Issue by mimimiaomiao1** [monlor/docker-xiaoya#246]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

![image](https://github.com/user-attachments/assets/a94bece2-5e70-4abc-8bf5-c629da00833b)

### 设备 (请填写以下信息)

Linux

**Comment by mimimiaomiao1** [comment]
就5678可以打开，可以播放，转存也OK。
2345，2346都打不开。

**Comment by mimimiaomiao1** [comment]
![image](https://github.com/user-attachments/assets/0ed50740-271c-4084-b116-f141395abdf4)
我是因为没有这个目录？还是因为他这个是系统盘里？我是不是应该给他改为外面的硬盘呢。

**Comment by zhoujian196622** [comment]
我的也是这样，你解决了吗

**Comment by hailinmail** [comment]
用webdav挂载后无法播放，日志记录报错：获取目录失败: object not found，解决了吗？哪里引起的问题？

**Comment by hailinmail** [comment]
用webdav挂载后无法播放，日志记录报错：获取目录失败: object not found，解决了吗？哪里引起的问题？
