### ISSUE TITLE
[FEATURE]: 大佬，能不能加上硬解呀，这个功能很重要

### ISSUE THREAD

**Issue by love-dy** [monlor/docker-xiaoya#249]
### 功能建议的描述

不转码看视频很卡

### 优先级

高

**Comment by love-dy** [comment]
docker-compose 修改后可以硬解，但一更新就要重新改，着实不方便呀大佬

**Comment by monlor** [comment]
现在增加了更新命令，`./manage.sh update`，不用覆盖配置
