### ISSUE TITLE
[BUG]: 为什么小雅的版本一直是0720

### ISSUE THREAD

**Issue by tyy840913** [monlor/docker-xiaoya#255]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

 [#小雅版本号没有更新]
![Screenshot_2024-09-14-13-41-47-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/86ab9f3e-d256-4998-b6ec-02e47fb5377f)

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
可能自动更新有问题，重启alist服务可以更新
