### ISSUE TITLE
[BUG]: Jellyfin元数据下载失败无限循环

### ISSUE THREAD

**Issue by imbayezi** [monlor/docker-xiaoya#265]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

一键部署后jellyfin无法打开部署，容器正常，元数据下载一直失败，还请大佬帮忙解答下怎么回事谢谢
系统：飞牛云OS

### 重现步骤

Status Legend:
(OK):download completed.
Download config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
Downloading config_jf.mp4, try 3...
Link is http://alist:5678/d/元数据/config_jf.mp4

10/17 11:00:39 [NOTICE] Downloading 1 item(s)

10/17 11:00:39 [NOTICE] Download complete: /media/temp/config_jf.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7ab38f|OK  |    12KiB/s|/media/temp/config_jf.mp4

Status Legend:
(OK):download completed.
Download config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.

### 预期行为

希望得到解答和反馈

### 截图

![QQ20241017-110040](https://github.com/user-attachments/assets/e897849d-949b-41fe-843a-3d6bd5f95de7)

### 日志

```shell
Status Legend:
(OK):download completed.
Download config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
Downloading config_jf.mp4, try 3...
Link is http://alist:5678/d/元数据/config_jf.mp4

10/17 11:00:39 [NOTICE] Downloading 1 item(s)

10/17 11:00:39 [NOTICE] Download complete: /media/temp/config_jf.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7ab38f|OK  |    12KiB/s|/media/temp/config_jf.mp4

Status Legend:
(OK):download completed.
Download config_jf.mp4 failed, file size less than 10M, retry after 10 seconds.
```

### 设备 (请填写以下信息)

Linux

**Comment by dingdayu** [comment]
请教这个得到缓解了吗？

**Comment by dingdayu** [comment]
请问问题缓解了吗？

**Comment by imbayezi** [comment]
> 请问问题缓解了吗？

没有，是小雅那边删除了Jellyfin的配置文件，所以不支持下载了

**Comment by wt7060** [comment]
> > 请问问题缓解了吗？
> 
> 没有，是小雅那边删除了Jellyfin的配置文件，所以不支持下载了

那就是小雅不支持了？？？
