### ISSUE TITLE
[BUG]: 在已安装jellyfin的情况下，选择xiaoya+jellyfin会因端口冲突导致安装中断

### ISSUE THREAD

**Issue by nathandingx** [monlor/docker-xiaoya#270]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

如题，我希望已有jellyfin不修改配置的情况下，能正常安装xiaoya+jellyfin

### 设备 (请填写以下信息)

其他（在其他信息中补充）

### 其他信息

UnRaid

**Comment by monlor** [comment]
jellyfin已经无法安装了，端口冲突问题使用手动安装修改端口解决
