### ISSUE TITLE
[BUG]: 新版xiaoya-alist-1需要密码

### ISSUE THREAD

**Issue by LastNever** [monlor/docker-xiaoya#281]
### 提交检查

- [x] 我已经搜索过 Issues，没有找到类似问题
- [x] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [x] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

新版xiaoya-alist-1需要密码，且通过docker exec -it xiaoya-alist-1 ./alist admin set  密码也是随机的，原版alist可以直接设置

### 截图

![image](https://github.com/user-attachments/assets/e0bfb145-05fa-40fe-97af-96c0835555c4)
![image](https://github.com/user-attachments/assets/79fd5bce-c616-4f96-991f-6342d108d5eb)

### 设备 (请填写以下信息)

Linux

**Comment by LastNever** [comment]
> 是用环境变量配置了密码么

没有
![image](https://github.com/user-attachments/assets/20bf1e38-d5b9-4b90-ab99-2df434f6fb8f)
![image](https://github.com/user-attachments/assets/d617bccf-9fd6-4da2-abaa-abc7fd09f8a9)

**Comment by monlor** [comment]
你设置了webdav_password 就会需要登录

**Comment by LastNever** [comment]
谢谢大佬，确实，删了就没了，不过我之前旧版镜像也设置了倒是没影响。
另外设置了webdav_password 密码就需要手动在后台获取一次alist的密码了，而且alist密码就不能自定义了，这个可能要在env里面说明一下

**Comment by LastNever** [comment]
感谢
