### ISSUE TITLE
[FEATURE]: 解决115网盘登录超时的问题

### ISSUE THREAD

**Issue by aflyingtree** [monlor/docker-xiaoya#290]
### 功能建议的描述

可以参考上游alist的115挂载的功能改进,针对115cookie添加新参数的场景进行处理.

### 功能背景

阿里云限速的情况下,实现115网盘的正常挂载使用.

### 预期的收益

实现115网盘的正常挂载.

### 实现建议

上游alist库已经有此问题的fix,希望大佬可以同步更新一下.
https://github.com/SheltonZhu/alist/commit/3c26ee4e993acb72af2613b609f52a7160b6916b

### 优先级

高

**Comment by monlor** [comment]
需要小雅那边先更新，我这里是每天自动同步小雅的最新版本

**Comment by aflyingtree** [comment]
小雅已更新.
