### ISSUE TITLE
PIKPAK目录无法显示

### ISSUE THREAD

**Issue by lqian8899** [monlor/docker-xiaoya#37]
修改了env文件中   PIKPAK_LIST=xxx@qq.com:password，PIKPAK目录无法显示，请问，格式是否正确？，谢谢

**Comment by monlor** [comment]
目录显示应该跟这个配置没有关系，问小雅吧

**Comment by lqian8899** [comment]
能否告我这个格式是否正确？
***@***.***:password




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "monlor/docker-xiaoya"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月4日(星期二) 凌晨1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [monlor/docker-xiaoya] PIKPAK目录无法显示 (Issue #37)





 
Closed #37 as completed.

**Comment by monlor** [comment]
没问题

**Comment by youngxlover** [comment]
我也有相同的问题，账号密码是正确的。 显示 /data/pikpak.txt: No such file or directory (os error 2)，xiaoya alist里，就没有出现pikpak

**Comment by monlor** [comment]
> 我也有相同的问题，账号密码是正确的。 显示 /data/pikpak.txt: No such file or directory (os error 2)，xiaoya alist里，就没有出现pikpak

看安装提示，修改需要执行reload生效

**Comment by Songkeys** [comment]
格式难道不是 `挂载名:账号:密码` 吗？

https://github.com/monlor/docker-xiaoya/blob/3a7b0d02a85053384203c21a75211047a080640b/alist/README.md?plain=1#L29
