### ISSUE TITLE
一键安装后 Emby 无法访问

### ISSUE THREAD

**Issue by heytl** [monlor/docker-xiaoya#38]
环境：谷歌云debian系统
安装方法：一键部署脚本，选择1 Xiaoya+Emby安装
问题：能通过ip:5678正常访问小雅Alist，但无法通过ip:6908访问Emby页面
配置有的的端口都开放了tcp:5678 tcp:6908 tcp:8096 tcp:2345 tcp:2346

**Comment by monlor** [comment]
先看日志，不是安装完立马就能访问

**Comment by heytl** [comment]
昨晚就安装了，我日志看不出来，能帮忙看一下吗
 /opt/xiaoya/manage.sh logs ：
![image](https://github.com/monlor/docker-xiaoya/assets/77422889/8931132e-1bc4-4ccc-a32b-8daeb184b56e)

emby容器日志
![image](https://github.com/monlor/docker-xiaoya/assets/77422889/26b39392-bc46-4bb9-9538-fa03c3591a87)

感谢大佬，回得真快

**Comment by monlor** [comment]
这应该是有个bug，我还没找到，你重启下emby服务就好了

**Comment by heytl** [comment]
好的，重启确实可以访问了。
赞一个，这个项目太方便了。
