### ISSUE TITLE
xiaoya alist怎么进入原版alist的管理端页面

### ISSUE THREAD

**Issue by lwydyby** [monlor/docker-xiaoya#45]
第一次部署xiaoya,没找到怎么进去alist管理端

**Comment by monlor** [comment]
小雅没有原版的管理界面

**Comment by lwydyby** [comment]
![image](https://github.com/monlor/docker-xiaoya/assets/30611869/e6ea72b6-5daf-4941-aab9-e4b79eeb93e4)
我看到了 是用nginx把管理页面给禁止了

**Comment by monlor** [comment]
哦哦，你可以尝试进一下，不过也没啥，可以在建一个alist来套娃小雅的 😂，很多人这么干的

**Comment by dhndzwxj** [comment]
> ![image](https://github.com/monlor/docker-xiaoya/assets/30611869/e6ea72b6-5daf-4941-aab9-e4b79eeb93e4) 我看到了 是用nginx把管理页面给禁止了，在容器的/etc/nginx/http.d/default.conf配置的

您好，我是用docker安装的xiaoya-alist，没有找到容器的`/etc/nginx/http.d/default.conf`文件，请问怎么办呢
