### ISSUE TITLE
我部署的是jellyfin，但没有显示jellyfin账号密码呢

### ISSUE THREAD

**Issue by lorna665** [monlor/docker-xiaoya#47]
我部署的是jellyfin，但没有显示jellyfin账号密码呢

**Comment by lorna665** [comment]
部署完成以后，无法正常播放。查看jellyfin日志。如下：
![1717583787898](https://github.com/monlor/docker-xiaoya/assets/145363899/3dbf1a8d-8cc8-476e-a93d-f21563216a4d)
![image](https://github.com/monlor/docker-xiaoya/assets/145363899/464f83e3-da6c-49f8-9fad-3fb7dc16ce64)
部署环境x86 debian 11

**Comment by monlor** [comment]
元数据确认下载完了吧，等一会再访问试试

**Comment by lorna665** [comment]
> 元数据确认下载完了吧，等一会再访问试试

早上装的，到现在应该下完了吧。不行我重装试试

**Comment by monlor** [comment]
早上的版本确实有问题，真要重装一下
