### ISSUE TITLE
Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated. 

### ISSUE THREAD

**Issue by HereNoAg300L** [monlor/docker-xiaoya#50]
Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated. 这个错误代码怎么解决

**Comment by monlor** [comment]
可能不影响使用吧

**Comment by monlor** [comment]
发布了新版本，之前jellyfin的媒体数据处理有问题，请重新安装新版本

**Comment by monlor** [comment]
先close了，新版本有问题再提
