### ISSUE TITLE
群晖环境下alist部署报错，报错如图

### ISSUE THREAD

**Issue by Sword6988** [monlor/docker-xiaoya#60]
![Snipaste_2024-06-06_15-02-45](https://github.com/monlor/docker-xiaoya/assets/93078948/7bd770cd-6ae7-4dce-87bf-90c327a7e391)

**Comment by monlor** [comment]
阿里云盘满了或者token等信息配置错误

**Comment by Sword6988** [comment]
没有满啊，我阿里云盘4个多T呢，才用了不到2t

**Comment by monlor** [comment]
换opentoken尝试

**Comment by ixxmu** [comment]
> 没有满啊，我阿里云盘4个多T呢，才用了不到2t
https://github.com/monlor/docker-xiaoya/issues/46
看这里
