### ISSUE TITLE
会不会加入签到呢

### ISSUE THREAD

**Issue by ixxmu** [monlor/docker-xiaoya#65]
**您的功能建议是否与某个问题有关？请描述。**
对问题的明确简洁描述。

**描述您想要的解决方案**
对您想要发生的事情的明确简洁描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的明确简洁描述。

**其他背景信息**
不知道签到还能有容量么，所以签到是否会加入？

感谢作者这么优雅的整合！

**Comment by monlor** [comment]
每天都会更新alist，自动重启alist，重启时就会签到

**Comment by hanlihanshaobo** [comment]
> 每天都会更新alist，自动重启alist，重启时就会签到

能否加一个开关，自主选择是否每天签到

**Comment by monlor** [comment]
> > 每天都会更新alist，自动重启alist，重启时就会签到
> 
> 
> 
> 能否加一个开关，自主选择是否每天签到

小雅不支持
