### ISSUE TITLE
新的bug

### ISSUE THREAD

**Issue by HereNoAg300L** [monlor/docker-xiaoya#66]
错误代码如下
ERRO[2024-06-06 10:54:14] failed get enabled storages: TokenVerifyFailed:The token was expected to have 3 parts, but got 1.
alist-1     | failed init storage
alist-1     | github.com/alist-org/alist/v3/internal/op.initStorage
alist-1     |   /app/internal/op/storage.go:99
alist-1     | github.com/alist-org/alist/v3/internal/op.LoadStorage
alist-1     |   /app/internal/op/storage.go:80
alist-1     | github.com/alist-org/alist/v3/internal/bootstrap.LoadStorages.func1
alist-1     |   /app/internal/bootstrap/storage.go:23
alist-1     | runtime.goexit
alist-1     |   /usr/lib/go/src/runtime/asm_arm64.s:1172 
甲骨文arm服务器 ubuntu22.04

**Comment by monlor** [comment]
换token 重启，请使用模板提issue
