### ISSUE TITLE
EmbyServer进程在闲置的时候高CPU占用

### ISSUE THREAD

**Issue by kqkq** [monlor/docker-xiaoya#69]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
使用docker-compose手动部署成功，近期发现EmbyServer进程CPU占用100%，内存占用2GB左右，机器无人访问，未处于播放状态。

查看Emby容器的日志，最新一条日志在2天前启动的时候，近期无日志产生。

请问EmbyServer在进行什么操作？如何排查？

**重现步骤**
复现问题的步骤:
使用top命令查看进程，并按CPU或内存占用排序，可见EmbyServer进程高资源占用

**预期行为**
Emby闲置时占用较少资源

**截图**
如果适用,添加截图以帮助解释您的问题。

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
无

**Comment by monlor** [comment]
emby可能会在后台自动扫描媒体库，媒体库每天凌晨自动更新
