### ISSUE TITLE
部署成功了，网页开小雅可以播放，但是emby点播放后一直转圈，后台看到缓存成功了，是需要开什么端口吗？

### ISSUE THREAD

**Issue by FANYT** [monlor/docker-xiaoya#78]
**提交检查**

- [* ] 确认你已经搜索过相关Issue，没有找到类似问题
- [ ] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [ ] 确认你已经删除底部的【常见问题】板块

**描述 bug**
部署成功了，网页开小雅可以播放，但是emby点播放后一直转圈，后台看到缓存成功了，是需要开什么端口吗？

**重现步骤**
复现问题的步骤:
1进入小雅网页版本，点击最新电影，可以看到后台缓存成功，页面播放正常
2进入emby，可以看到服务器影片列表，点击电影，可以看到后台缓存成功，但是播放器一直转圈

**截图**
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/3c9f5fa4-f9f2-4eca-9647-1bd755bcc4dc)

![image](https://github.com/monlor/docker-xiaoya/assets/9249921/2456dfd4-7332-42bd-b374-17c57896fd0a)

![image](https://github.com/monlor/docker-xiaoya/assets/9249921/5f5b2438-7dce-4d19-8799-2536d43bf5da)

![image](https://github.com/monlor/docker-xiaoya/assets/9249921/ec2c342a-9abc-4e09-8931-db5e72b12b15)

**设备 (请填写以下信息):**
 - [ *] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**Comment by FANYT** [comment]
补充一下，用potplayer连接webdav也是可以播放的

**Comment by FANYT** [comment]
默认的2345

**Comment by FANYT** [comment]
会不会是这个问题，emby播放，一转存完就提示清理掉了
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/9b08cfee-ec20-4f48-be08-f2b6f4c9ec0a)
网页播放就没有马上提示清理
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/d4621d43-8e55-49a7-a2cb-605c1ffcffe0)

**Comment by monlor** [comment]
是偶发么

**Comment by monlor** [comment]
播放多等一会 emby播放比较慢

**Comment by FANYT** [comment]
> 是偶发么

一直这样，不是偶发，我刚刚还重新跑了脚本更新了一下，还是这样，不知道其它人有没有碰到

**Comment by monlor** [comment]
> > 是偶发么
> 
> 
> 
> 一直这样，不是偶发，我刚刚还重新跑了脚本更新了一下，还是这样，不知道其它人有没有碰到

看一下alist的nginx日志，在/var/log/nginx/error.log

**Comment by FANYT** [comment]
> > > 是偶发么
> > 
> > 
> > 一直这样，不是偶发，我刚刚还重新跑了脚本更新了一下，还是这样，不知道其它人有没有碰到
> 
> 看一下alist的nginx日志，在/var/log/nginx/error.log

没有这个路径
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/7c6d76c8-bee6-4d62-a39f-ca36c58659d6)

**Comment by monlor** [comment]
看容器xiaoya-alist-1里面的nginx日志

**Comment by FANYT** [comment]
> 看容器xiaoya-alist-1里面的nginx日志
2024/06/07 11:48:16 [error] 439#439: *1528 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:50:10 [warn] 440#440: *1710 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000756, client: 120.41.227.170, server: default, request: "POST /emby/DisplayPreferences/usersettings?userId=40a02f8503ce4de49d58331a282dcea1&client=emby&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-GG0I3B4&X-Emby-Device-Id=DESKTOP-GG0I3B4&X-Emby-Client-Version=3.0.19-2.1&X-Emby-Token=ab4445575d3441ebb149776cd42a7cd3&reqformat=json HTTP/1.1", host: "xiaoya.tttvm.vip:2345"
2024/06/07 11:50:13 [warn] 440#440: *1725 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000757, client: 120.41.227.170, server: default, request: "POST /emby/DisplayPreferences/usersettings?userId=40a02f8503ce4de49d58331a282dcea1&client=emby&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-GG0I3B4&X-Emby-Device-Id=DESKTOP-GG0I3B4&X-Emby-Client-Version=3.0.19-2.1&X-Emby-Token=ab4445575d3441ebb149776cd42a7cd3&reqformat=json HTTP/1.1", host: "xiaoya.tttvm.vip:2345"
2024/06/07 11:50:27 [error] 440#440: *1829 js: itemInfoUri: EMBY_SERVER/emby/Items/593977/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:50:27 [error] 440#440: *1829 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:52:14 [error] 440#440: *1921 js: itemInfoUri: EMBY_SERVER/emby/Items/1692351/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:52:14 [error] 440#440: *1921 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:54:10 [error] 441#441: *1950 js: itemInfoUri: EMBY_SERVER/emby/Items/1692351/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:54:10 [error] 441#441: *1950 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:56:36 [error] 442#442: *2094 js: itemInfoUri: EMBY_SERVER/emby/Items/1692351/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:56:36 [error] 442#442: *2094 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:57:38 [error] 442#442: *2130 js: itemInfoUri: EMBY_SERVER/emby/Items/1692351/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:57:38 [error] 442#442: *2130 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 11:59:56 [error] 442#442: *2177 js: itemInfoUri: EMBY_SERVER/emby/Items/1692351/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 11:59:56 [error] 442#442: *2177 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 12:01:06 [error] 442#442: *2210 js: itemInfoUri: EMBY_SERVER/emby/Items/1777495/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 12:01:06 [error] 442#442: *2210 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 12:13:17 [error] 439#439: *2288 js: itemInfoUri: EMBY_SERVER/emby/Items/1606764/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 12:13:17 [error] 439#439: *2288 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 13:07:23 [error] 442#442: *2404 js: itemInfoUri: EMBY_SERVER/emby/Items/1606764/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 13:07:23 [error] 442#442: *2404 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 13:10:04 [error] 442#442: *2415 js: itemInfoUri: EMBY_SERVER/emby/Items/1572528/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 13:10:04 [error] 442#442: *2415 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 13:19:05 [error] 439#439: *2504 js: itemInfoUri: EMBY_SERVER/emby/Items/1606764/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 13:19:05 [error] 439#439: *2504 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix
2024/06/07 13:22:27 [error] 440#440: *2549 js: itemInfoUri: EMBY_SERVER/emby/Items/1572504/PlaybackInfo?api_key=ab4445575d3441ebb149776cd42a7cd3
2024/06/07 13:22:27 [error] 440#440: *2549 js: error: emby_api fetch mediaItemInfo failed,  Error: unsupported URL prefix

**Comment by monlor** [comment]
你是用一键脚本安装的么？ 在alist容器里面执行这个命令看看：`/update_media_addr.sh`

**Comment by FANYT** [comment]
> 你是用一键脚本安装的么？ 在alist容器里面执行这个命令看看：`/update_media_addr.sh`

是的，这个脚本
export GH_PROXY=https://gh.monlor.com/ IMAGE_PROXY=ghcr.monlor.com && bash -c "$(curl -fsSL ${GH_PROXY}https://raw.githubusercontent.com/monlor/docker-xiaoya/main/install.sh)"
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/2195df4e-c95b-48e8-9ff2-fea9c8f42d46)

**Comment by monlor** [comment]
你的docker网络有问题呀，是不是没关防火墙，服务之前网络都不通

**Comment by FANYT** [comment]
> 你的docker网络有问题呀，是不是没关防火墙，服务之前网络都不通

docker的网络没有弄过，就是默认用脚本安装的，要在三个docker的命令行关闭防火墙吗？

**Comment by monlor** [comment]
> > 你的docker网络有问题呀，是不是没关防火墙，服务之前网络都不通
> 
> 
> 
> docker的网络没有弄过，就是默认用脚本安装的，要在三个docker的命令行关闭防火墙吗？
> 
> 
> 
> 

我看错了 这个没问题

**Comment by monlor** [comment]
看一下这个文件里的embyhost值是啥，也是alist容器

/etc/nginx/http.d/emby.js

**Comment by FANYT** [comment]
> 看一下这个文件里的embyhost值是啥，也是alist容器
> 
> /etc/nginx/http.d/emby.js

![image](https://github.com/monlor/docker-xiaoya/assets/9249921/4cbda20a-3727-4ea0-8210-b8e7d0772f56)

**Comment by monlor** [comment]
重启alist应该就好了

**Comment by FANYT** [comment]
还是转圈，日志有变化
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/ee092894-7ef9-4870-a6c6-bf137547d431)

**Comment by monlor** [comment]
正常了吧，换资源，有的资源不行

**Comment by monlor** [comment]
等明天，数据更新后再看看，现在一些资源还是老的

**Comment by FANYT** [comment]
终于找到一个可以播放的，就是元数据是乱的，播放的是不成问题的问题，元数据显示莫斯科行动
![image](https://github.com/monlor/docker-xiaoya/assets/9249921/7e855e29-664e-4067-9712-1f185e6df0cf)

**Comment by Songkeys** [comment]
请问你解决了吗？我发现 dav 没有任何问题。但是 emby 就是看不了任何东西，也无法下载（0%）。在 emby 网页版会提示没有兼容的流；客户端会直接退出来；infuse 里会弹窗 An error occurred loading this content，并且所有影片大小都显示 0.0kb。

日志里没有报错，而且和你一样，网盘有缓存到影片，但就是放不出来 ：（

**Comment by nomedia** [comment]
我也一样的问题
