### ISSUE TITLE
是不是不支持海报墙

### ISSUE THREAD

**Issue by ixxmu** [monlor/docker-xiaoya#80]
**您的功能建议是否与某个问题有关？请描述。**
对问题的明确简洁描述。

**描述您想要的解决方案**
对您想要发生的事情的明确简洁描述。

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的明确简洁描述。

**其他背景信息**
已经尝试看了原版小雅的教程，想在tvbox上配置出来海报墙，是不是不支持呢？

**Comment by monlor** [comment]
暂时不对tvbox提供额外支持，目前只有小雅自带的tvbox
