### ISSUE TITLE
metadata报错xiaoya-metadata-1 exited with code 137

### ISSUE THREAD

**Issue by u2o** [monlor/docker-xiaoya#81]
测试alist+metadata+jellyfin, metedata不断会报错然后重启。

xiaoya-metadata-1  | /entrypoint.sh: line 59:    20 Killed                  aria2c -o "${file}" --allow-overwrite=true --auto-file-renaming=false --enable-color=false -c -x6 "${ALIST_ADDR}/d/元数据/${path}${file}"
xiaoya-metadata-1 exited with code 137
xiaoya-metadata-1  | alist启动完成，可能需要一段时间加载数据，等待5分钟后开始下载元数据..

**Comment by monlor** [comment]
请使用模板提问题
