### ISSUE TITLE
已购买高级版Key，但客户端报错Emby Premiere无效

### ISSUE THREAD

**Issue by szsong** [monlor/docker-xiaoya#82]
已购买高级版Key，但客户端报错Emby Premiere无效

服务器端正常显示金色badge，也都有高级版功能的入口

但是Android版客户端无法使用任何高级版功能
![Screenshot_20240608_165147](https://github.com/monlor/docker-xiaoya/assets/3055084/dd8a7de7-ab60-47f2-8611-deff8b54fe3d)

**Comment by monlor** [comment]
小雅本身config数据的问题，我也遇到这个问题，没找到解决办法

**Comment by szsong** [comment]
很尴尬，
又一次的。。。重启容器几次以后莫名其妙的好了

有可能跟Android客户端版本有关？之前是3.4.xx
手动安装了3.3.95,一开始问题依旧但是过了大约一天就好了

**Comment by lxz946786639** [comment]
检查一下deviceId吧哥们儿

**Comment by szsong** [comment]
> 检查一下deviceId吧哥们儿

兄台请指教。。。具体检查什么呢？谢谢

**Comment by szsong** [comment]
> 很尴尬， 又一次的。。。重启容器几次以后莫名其妙的好了
> 
> 有可能跟Android客户端版本有关？之前是3.4.xx 手动安装了3.3.95,一开始问题依旧但是过了大约一天就好了

Update:
好了没多久又坏了

大部分时间都是不好的，极少数情况下突然会好。。。。

**Comment by star8618** [comment]
群辉硬解怎么搞

**Comment by gaomianyangsb** [comment]
把emby配置里的device.txt删除，然后重启emby，再重新输入emby的激活码激活一下就好了。
这个文件里面的内容是你设备的ID，emby也是根据这个来辨别设备的。但是因为用脚本部署的enby都是打包的小雅大佬的emby，所以里面的deviceID都是小雅大大的，相当于在emby官方看来你是在和很多人共用一个ID。把这个文件删除之后重启，emby会自动创建一个新的device.txt，这里面的ID就是你的设备专属的了，再重新激活一下就没问题了。
（如果不放心的话可以先把原device.txt备份一下再删除）

**Comment by monlor** [comment]
> 把emby配置里的device.txt删除，然后重启emby，再重新输入emby的激活码激活一下就好了。
> 
> 这个文件里面的内容是你设备的ID，emby也是根据这个来辨别设备的。但是因为用脚本部署的enby都是打包的小雅大佬的emby，所以里面的deviceID都是小雅大大的，相当于在emby官方看来你是在和很多人共用一个ID。把这个文件删除之后重启，emby会自动创建一个新的device.txt，这里面的ID就是你的设备专属的了，再重新激活一下就没问题了。
> 
> （如果不放心的话可以先把原device.txt备份一下再删除）

我这样操作过，好像不行

**Comment by sanfordkai** [comment]
> 群辉硬解怎么搞

同求

**Comment by monlor** [comment]
终于知道啥问题了，我之前改正版镜像没改成功，一直用的开心版镜像，导致无法使用激活码。最新的测试版已经改过来了，默认部署emby使用正版镜像。
