### ISSUE TITLE
metadata-1  | ERROR: Data Error报错

### ISSUE THREAD

**Issue by CharliesTONG** [monlor/docker-xiaoya#84]
metadata-1  | ERROR: Data Error : 每日更新/动漫/日本/2023/海贼王 (1999)/S21/S21E1069.strm
ubuntu22.04
有很多这种类似报错，且重复执行依旧报错
media文件夹下没有文件
![Uploading 屏幕截图 2024-06-09 182157.png…]()

**Comment by monlor** [comment]
请使用问题模板提问，图片没有展示出来
