### ISSUE TITLE
emby可否使用自定义镜像？

### ISSUE THREAD

**Issue by zzk1996** [monlor/docker-xiaoya#86]
如题，部署时想使用第三方的emby
更改compose文件里的emby镜像以及env文件emby的地址是否会对使用上产生影响？

**Comment by monlor** [comment]
不行，emby是专门为小雅做适配的，有提供一个第三方镜像选择：https://github.com/monlor/docker-xiaoya/tree/main/emby

**Comment by zzk1996** [comment]
好的
