### ISSUE TITLE
高频率遇到docker.xiaoya.pro可用性问题，建议提供自动重启时间的设置

### ISSUE THREAD

**Issue by kqkq** [monlor/docker-xiaoya#87]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
屡次遇到小雅Alist重启后更新失败的问题，经过分析日志，发现是docker.xiaoya.pro报503错误。过几小时后手工重启容器，恢复正常。

分析原因应该是大量的xiaoya容器在凌晨2点重启，集中请求docker.xiaoya.pro导致服务不可用。

是否有办法设置xiaoya容器的自动重启时间？例如手工更改到凌晨4点左右？

**重现步骤**
复现问题的步骤:
1. 在凌晨2点重启xiaoya容器

**预期行为**
资源正常加载

**截图**
N/A

**设备 (请填写以下信息):**
 - [ ] Linux
 - [ ] Windows
 - [ ] Mac
 - [x] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
在此添加有关问题的任何其他上下文。

**Comment by monlor** [comment]
目前是凌晨3点更新数据并重启，可以考虑使用随机时间
