### ISSUE TITLE
部分图片显示不出来

### ISSUE THREAD

**Issue by Narutojoy** [monlor/docker-xiaoya#88]
**提交检查**

- [x] 确认你已经搜索过相关Issue，没有找到类似问题
- [x] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [x] 确认你已经删除底部的【常见问题】板块

**描述 bug**
部分图片显示不出来，如下图所示

**重现步骤**
复现问题的步骤:
1. Docker-compose部署完后进入emby后台，部分图片无法显示
2. 已经重新安装过一遍，问题依旧
3. 不能显示图片的剧集，两次重装后均相同

**预期行为**
图片正常显示

**截图**
![Screenshot_20240610-163610](https://github.com/monlor/docker-xiaoya/assets/25220944/17bf343d-7887-4ce3-934e-acd70cb23d62)

**设备 (请填写以下信息):**
 - [x] Linux
 - [ ] Windows
 - [ ] Mac
 - [ ] 群晖
 - [ ] 绿联
 - [ ] 其他（在下面填写）

**其他信息**
无其它问题

---

**Comment by Narutojoy** [comment]
找了下规律，貌似是路径问题
凡是如图所示的都是不能播放，没有图片
![Screenshot_20240610-191506~2](https://github.com/monlor/docker-xiaoya/assets/25220944/da02dc72-92d7-4986-a296-0ff7216d1a9c)

怀疑是我改了docker-compose的路径，每个路径前加了个./表示当前目录

但我又重装了一遍，用的一键脚本，路径填了自定义路径，问题依旧。

然后我又重装了一遍，这次用的手动配置docker-compose方法，没问题了

但我还是想自定义路径，大大能不能帮忙看看问题呀

**Comment by monlor** [comment]
等数据第二天自动更新可能就好了

**Comment by Narutojoy** [comment]
> 等数据第二天自动更新可能就好了

Okk我再试试

**Comment by Narutojoy** [comment]
> 等数据第二天自动更新可能就好了

大佬我又看了一遍，那些显示不出来的文件路径都不是https://xiaoya开头的，凡是https://xiaoya开头的都没问题。
这个等第二天真的有效嘛，还是说我设置有问题呀。
或者说我怎么手动刷新嘞

**Comment by monlor** [comment]
不是xiaoya开头是什么地址，发出来看看

**Comment by Narutojoy** [comment]
> 不是xiaoya开头是什么地址，发出来看看

这样的（这种都是不能播放的而且封面破损的
![image](https://github.com/monlor/docker-xiaoya/assets/25220944/bdb1fbc1-e776-4d73-acb4-33504ecabcbb)

**Comment by monlor** [comment]
这是正常的

**Comment by Narutojoy** [comment]
> 这是正常的

okkk 那我再等等看
顺便问问大佬，有交流群吗哈哈哈哈哈

**Comment by monlor** [comment]
![image](https://github.com/monlor/docker-xiaoya/assets/20394007/9bc4c4be-7f50-4bda-9e40-a683474cde3a)
有一个之前建的内测群

**Comment by Narutojoy** [comment]
已加群聊，多谢大佬！
