### ISSUE TITLE
今攻再看還是502，

### ISSUE THREAD

**Issue by mackamvenus** [monlor/docker-xiaoya#89]
今攻再看還是502，
打docker ps 看以下結果

CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS                    PORTS                                                                                                      NAMES
1eac361d3f07   ghcr.monlor.com/monlor/xiaoya-jellyfin:latest   "/entrypoint.sh"         22 hours ago   Up 22 hours (unhealthy)   0.0.0.0:8096->8096/tcp, :::8096->8096/tcp                                                                  xiaoya-jellyfin-1

_Originally posted by @mackamvenus in https://github.com/monlor/docker-xiaoya/issues/85#issuecomment-2158094585_

**Comment by monlor** [comment]
请使用模板提问题，这样提我没办法解答
