### ISSUE TITLE
部署后emby点击播放后会提示“播放错误 当前没有兼容的流”

### ISSUE THREAD

**Issue by caiz0723** [monlor/docker-xiaoya#90]
**提交检查**

- [是] 确认你已经搜索过相关Issue，没有找到类似问题
- [是] 确认你已经检查过当前页面底部的常见问题列表，没有找到类似问题
- [是] 确认你已经删除底部的【常见问题】板块

**描述 bug**
我这边部署完能顺利进入emby，但点击播放后会提示“播放错误 当前没有兼容的流”，看日志的话，我播放时候xiaoya已经缓存视频到我云盘里了，但缓存成功后就执行了清除命令，彻底删除文件【见图三】。

**重现步骤**
复现问题的步骤:
我是直接用ssh进行部署，不懂代码所以都是默认进行，期间出现两类错误，不知是否与无法播放相关
1. 设置服务部署目录是显示错误代码，见图1
2. 部署完成后，显示无法执行get header命令，见图2
3. 在emby播放显示播放错误，日志见图3

**预期行为**
希望能解答以上，看是我哪里处理错误。

**截图**
图1
![1](https://github.com/monlor/docker-xiaoya/assets/172272958/8059a166-aa25-4393-ac3d-eee504034cb4)
图2
![2](https://github.com/monlor/docker-xiaoya/assets/172272958/6d7e5d76-308f-4b5f-b6ce-e8fb2eef5411)
图3
![3](https://github.com/monlor/docker-xiaoya/assets/172272958/35d6cab5-5d2c-45f4-a962-98bfa08078c4)

**设备 (请填写以下信息):**

 - [y] 群晖

感谢！

**Comment by monlor** [comment]
emby播放时查看alist中的nginx日志：/var/log/nginx/error.log

**Comment by legendzyb** [comment]
我也遇到了这个问题

**Comment by caiz0723** [comment]
> emby播放时查看alist中的nginx日志：/var/log/nginx/error.log

不是很懂，我用终端用cat /var/log/nginx/error.log弄出来很多日志看着和alist和emby无关。我在谷歌搜了下问题，看到这个https://github.com/bpking1/embyExternalUrl/issues/106  可能是浏览器的问题吧，后边我在TV上安装了emby，是可以正常观看的，理论上是部署成功的。所以还是感谢大大提供这个工具，特别是现在拉不了docker的情况下👍

**Comment by LaelLuo** [comment]
这个基本都是视频的格式emby网页版不兼容啥的 但实际上应该兼容才对 毕竟小雅的网页能直接播
猜测可能是因为emby读取文件的方式不是使用视频的读取方式 导致没有视频加速啥的 我播放的时候也会卡卡的 使用vlc或者直接小雅网页播放就没这个问题
但这就不是这边能修的了 直接用客户端播放就不会有这个问题

**Comment by monlor** [comment]
> 这个基本都是视频的格式emby网页版不兼容啥的 但实际上应该兼容才对 毕竟小雅的网页能直接播
> 
> 猜测可能是因为emby读取文件的方式不是使用视频的读取方式 导致没有视频加速啥的 我播放的时候也会卡卡的 使用vlc或者直接小雅网页播放就没这个问题
> 
> 但这就不是这边能修的了 直接用客户端播放就不会有这个问题

是的
