### ISSUE TITLE
再看還是502 bad gateway

### ISSUE THREAD

**Issue by mackamvenus** [monlor/docker-xiaoya#91]
打docker ps 看以下結果

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
1eac361d3f07 ghcr.monlor.com/monlor/xiaoya-jellyfin:latest "/entrypoint.sh" 22 hours ago Up 22 hours (unhealthy) 0.0.0.0:8096->8096/tcp, :::8096->8096/tcp xiaoya-jellyfin-1

**Comment by monlor** [comment]
请使用模板提问题，提供容器日志
