### ISSUE TITLE
修改小雅alist的状态检查逻辑

### ISSUE THREAD

**Issue by monlor** [monlor/docker-xiaoya#98]
**您的功能建议是否与某个问题有关？请描述。**

**描述您想要的解决方案**

alist存活判断逻辑：`http://alist:5678/api/public/settings` 返回`.code=200`

1. alist增加一个进程守护，保活
2. emby、jellyfin、metadata对alist的存活检测逻辑修改

**描述您考虑过的替代方案**
对您考虑过的任何替代解决方案或功能的明确简洁描述。

**其他背景信息**
在此添加任何其他与该功能建议有关的内容或截图。

**Comment by sss128** [comment]
healthcheck:
      test: ["CMD-SHELL", "curl --silent --show-error --fail http://localhost/api/public/settings | grep 200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
